// generated by sqlhelp; DO NOT EDIT
package user

type _PersonColumn struct {
	Fname string
}

type _UserColumn struct {
	ID string

	Name string
}

var (
	PersonColumns _PersonColumn

	UserColumns _UserColumn
)

func init() {

	// define Person column names

	PersonColumns.Fname = "fname"

	// define User column names

	UserColumns.ID = "json_id"

	UserColumns.Name = "json_name"

}
