// generated by sqlhelp; DO NOT EDIT
package user

type _UserColumn struct {
	ID string

	Name string
}

var (
	UserColumns _UserColumn
)

func init() {

	// define User column names

	UserColumns.ID = "id"

	UserColumns.Name = "nickname"

}
